In [84]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split

In [92]:
dataset = pd.read_csv('iris-species/Iris.csv')
dataset = dataset.iloc[:,1:].values

X_train = dataset[:, : -1]
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)

labelencoder_y = LabelEncoder()
dataset[:, 4] = labelencoder_y.fit_transform(dataset[:, 4])


onehotencoder = OneHotEncoder(categorical_features = [4])
Y = onehotencoder.fit_transform(dataset).toarray()[:,:3]

X_train, X_test, y_train, y_test = train_test_split(X_train, Y, test_size = 0.2, random_state = 0)

print(X_test)

kmeans = KMeans(n_clusters=3, random_state=0).fit(X_train)

print(kmeans.predict([-5.25060772e-02, -5.87763531e-01,   7.62758643e-01,   1.57942861e+00]))

[[ -5.25060772e-02  -5.87763531e-01   7.62758643e-01   1.57942861e+00]
 [  1.89829664e-01  -1.97618132e+00   1.37235899e-01  -2.61192967e-01]
 [ -4.16009689e-01   2.65187798e+00  -1.34127240e+00  -1.31297673e+00]
 [  1.76501198e+00  -3.56360566e-01   1.44514709e+00   7.90590793e-01]
 [ -1.02184904e+00   8.00654259e-01  -1.28440670e+00  -1.31297673e+00]
 [  5.53333275e-01   5.69251294e-01   1.27454998e+00   1.71090158e+00]
 [ -1.02184904e+00   1.03205722e+00  -1.39813811e+00  -1.18150376e+00]
 [  1.03800476e+00   1.06445364e-01   5.35295827e-01   3.96171883e-01]
 [  1.15917263e+00  -5.87763531e-01   5.92161531e-01   2.64698913e-01]
 [  3.10997534e-01  -5.87763531e-01   1.37235899e-01   1.33225943e-01]
 [  3.10997534e-01  -1.05056946e+00   1.04708716e+00   2.64698913e-01]
 [  6.74501145e-01   3.37848329e-01   4.21564419e-01   3.96171883e-01]
 [  3.10997534e-01  -5.87763531e-01   5.35295827e-01   1.75297293e-03]
 [  7.95669016e-01  -5.87763531e-01   4.78430123e-01   3.96171883e-01]
 [  3.

/home/tikou/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


ValueError: Expected 2D array, got 1D array instead:
array=[-0.05250608 -0.58776353  0.76275864  1.57942861].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.